### ISSUE TITLE
horizontal overflow (powersystems)

### ISSUE THREAD

**Issue by tlienart** [NREL-SIIP/SIIP-Tutorial#2]
Looking at https://nrel-siip.github.io/SIIP-Tutorial/powersystems/ you might want to place the result in an iframe or something and get it to have a scrollable horizontal overflow, otherwise it looks like this 

<img width="1311" alt="Screenshot 2022-03-08 at 15 59 22" src="https://user-images.githubusercontent.com/10897531/157263982-6effe3a9-de64-4489-b40a-53f03c34dea1.png">

I *think* this can be done adjusting some of the CSS but might require a bit of fiddling

**Comment by kdheepak** [comment]
I was going to look into how to breakout of the layout and adjust the CSS, but an iframe could be a good alternative.

**Comment by kdheepak** [comment]
Not ideal yet, but an improvement. 

![Screen Shot 2022-03-08 at 11 38 33 AM](https://user-images.githubusercontent.com/1813121/157303601-90305a53-25f1-4347-8253-7725759820c9.png)

I added a `full-width` css class to break out of the layout using help from https://css-tricks.com/full-width-containers-limited-width-parents/

The D3 code isn't working for zooming in and panning. But that's for me to figure out another day.

Thanks for reporting. I'm going to close this for now.
